apiVersion: v1
kind: ConfigMap
metadata:
  name: gedtotal-ocr-service-config
  namespace: gedtotalapi-apps
data:
  SERVER_PORT: "8093"
  KAFKA_BOOTSTRAP_SERVERS: "15.229.173.87:19092"
  KAFKA_INPUT_TOPIC: "arquivos-processar-gedtotal-ocr"
  KAFKA_OUTPUT_TOPIC: "extrair-texto-pdf"
  KAFKA_FAILURE_TOPIC: "arquivos-processar-gedtotal-ocr-falha"
  KAFKA_GROUP_ID: "gedtotal-ocr-service"
  AWS_REGION: "sa-east-1"
  S3_BUCKET: "gedtotal"
  OCR_LANGUAGE: "por"
  OCR_JOBS: "8"
  OCR_OUTPUT_TYPE: "pdfa"
  OCR_FORCE: "true"
  OCR_ROTATE_PAGES: "true"
  OCR_CLEAN: "true"
  OCR_OPTIMIZE: "3"
  OCR_USE_THREADS: "true"
  OCR_OVERWRITE_SOURCE: "true"
  OCR_OUTPUT_SUFFIX: "-ocr"
  LOG_LEVEL: "INFO"
