apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - gedtotal-ocr-service-configmap.yml
  - secret-template.yaml
images:
  - name: docker.io/eurival/gedtotal-ocr-service
    newTag: 20260401.221223-f0b22a1
namespace: gedtotalap-apps
