apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - gedtotal-ocr-service-configmap.yml
  # secret gerenciado manualmente no cluster (kubectl create secret)
  # - secret-template.yaml
images:
  - name: docker.io/eurival/gedtotal-ocr-service
    newTag: 20260430.012937-cd144bb
namespace: gedtotalapi-apps
