apiVersion: v1
kind: ConfigMap
metadata:
  name: licitai-documento-ocr-service-config
  namespace: gedtotalapi-apps
data:
  APP_NAME: "licitai-documento-ocr-service"
  SERVER_PORT: "8093"
  KAFKA_BOOTSTRAP_SERVERS: "15.229.173.87:19092"
  KAFKA_INPUT_TOPIC: "licitai.documento.ocr.solicitado"
  KAFKA_OUTPUT_TOPIC: "licitai.documento.ocr.processado"
  KAFKA_FAILURE_TOPIC: "licitai.documento.ocr.falhou"
  KAFKA_GROUP_ID: "licitai-documento-ocr-service"
  KAFKA_AUTO_OFFSET_RESET: "earliest"
  STORAGE_PROVIDER: "s3"
  S3_ENDPOINT: "https://object.sp2.eveo.com.br"
  S3_BUCKET: "licitaglobal"
  S3_REGION: "auto"
  S3_PATH_STYLE: "true"
  S3_VERIFY_SSL: "true"
  S3_ALLOWED_PREFIX: "documentos/"
  OCR_LANGUAGE: "por"
  OCR_JOBS: "8"
  OCR_OUTPUT_TYPE: "pdfa"
  OCR_FORCE: "true"
  OCR_ROTATE_PAGES: "true"
  OCR_CLEAN: "true"
  OCR_OPTIMIZE: "3"
  OCR_USE_THREADS: "true"
  OCR_OVERWRITE_SOURCE: "false"
  OCR_OUTPUT_SUFFIX: "-ocr"
  LOG_LEVEL: "INFO"
