apiVersion: v1
kind: Service
metadata:
  name: licitai-ocr-service
  namespace: gedtotalapi-apps
  labels:
    app: licitai-ocr-service
spec:
  selector:
    app: licitai-ocr-service
  ports:
    - name: http
      port: 8093
      targetPort: 8093
  type: ClusterIP
