apiVersion: v1
kind: ConfigMap
metadata:
  name: licitai-ocr-service-config
  namespace: gedtotalapi-apps
data:
  APP_NAME: "licitai-ocr-service"
  SERVER_PORT: "8093"
  KAFKA_BOOTSTRAP_SERVERS: "15.229.173.87:19092"
  KAFKA_INPUT_TOPIC: "licitai.ocr.requests"
  KAFKA_OUTPUT_TOPIC: "licitai.ocr.results"
  KAFKA_FAILURE_TOPIC: "licitai.ocr.failures"
  KAFKA_GROUP_ID: "licitai-ocr-service"
  AWS_REGION: "sa-east-1"
  S3_BUCKET: "licitai-ai-processing"
  OCR_LANGUAGE: "por"
  OCR_JOBS: "8"
  OCR_OUTPUT_TYPE: "pdfa"
  OCR_FORCE: "true"
  OCR_ROTATE_PAGES: "true"
  OCR_CLEAN: "true"
  OCR_OPTIMIZE: "3"
  OCR_USE_THREADS: "true"
  OCR_OVERWRITE_SOURCE: "false"
  OCR_OUTPUT_SUFFIX: "-ocr"
  LOG_LEVEL: "INFO"
