apiVersion: v1
kind: Secret
metadata:
  name: licitai-documento-ocr-service-secrets
  namespace: gedtotalapi-apps
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<YOUR_LICITAI_DOCUMENTO_AWS_ACCESS_KEY_ID>"
  AWS_SECRET_ACCESS_KEY: "<YOUR_LICITAI_DOCUMENTO_AWS_SECRET_ACCESS_KEY>"
  # Opcional, descomente se for utilizar token de sessao temporario
  # AWS_SESSION_TOKEN: "<YOUR_AWS_SESSION_TOKEN>"
