apiVersion: v1
kind: Secret
metadata:
  name: gedtotal-ocr-service-secrets
  namespace: gedtotalap-apps
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "REPLACE_ME"
  AWS_SECRET_ACCESS_KEY: "REPLACE_ME"
