apiVersion: v1
kind: Service
metadata:
  name: gedtotal-ocr-service
  namespace: gedtotalap-apps
  labels:
    app: gedtotal-ocr-service
spec:
  selector:
    app: gedtotal-ocr-service
  ports:
    - name: http
      port: 8093
      targetPort: 8093
  type: ClusterIP
